### PR TITLE
topic/yaml should trigger builds

### PR DESCRIPTION
**Pull request by jdshkolnik**

### CODE REVIEW

**Comment by jdshkolnik** [comment]
@ornatwork please review. We can discuss this before you approve anything.

**Comment by jdshkolnik** [comment]
You're a build administrator so it's not a permission issue.

**Comment by jdshkolnik** [comment]
Why are you still messing with the old build?

**Comment by jdshkolnik** [comment]
I got the tests to run. We should discuss designating something as a release-to-market build.

**Comment by ornatwork** [comment]
> Why are you still messing with the old build?



> Why are you still messing with the old build?

Trying to compare then on V2

**Pull request merged**
